### ISSUE TITLE
i18n or l10n?

### ISSUE THREAD

**Issue by ghost** [LeonMrBonnie/altv-os-i10n#1]
Not to come off like a total dick or anything, but this plugin is l10n (localization) and not i18n (internationalization).
i18n would not merely translate text, it would also convert units, time formats, date formats etc.

You can read more about it here: https://blog.mozilla.org/l10n/2011/12/14/i18n-vs-l10n-whats-the-diff/

**Comment by LeonMrBonnie** [comment]
Renamed it.
